### ISSUE TITLE
SplitFactory blocking protractor tests

### ISSUE THREAD

**Issue by rbobko93** [splitio/angular-sdk-examples#11]
Hey,

Hope all of you are doing great. Me and my team are using SplitIO in our project. Angular 8 created with JHipster, but I don't think it matters. Issue that we are facing is that when splitio service/client is running it is blocking our e2e (protractor) tests to perform any actions, like clicking on the button or navigating on the page.

Specifically invoking this line causes tests to start breaking:
```
SplitFactory({
      ...config
    });
```

I am not sure why this would be happening and I would really appreciate any help. If you need more information just let me know.

**Comment by aaroncadrian** [comment]
I am experiencing this same issue.

See [9.5.4 Highway to the Angular zone](https://livebook.manning.com/book/testing-angular-applications/chapter-9/98) for more information as to why this is happening. It has to do with Split.io's polling using `setTimeout`.

**Comment by rbobko93** [comment]
Thanks for the response. I have already solved this issue following instructions from this link: https://github.com/angular/protractor/blob/master/docs/timeouts.md#angular

Just forgot to post it here. I think it's safe to close.
